version: "3.7"
services:
   monitor_contingencia:
      container_name: monitor_contingencia
      image: monitor_contingencia:V1
      network_mode: host
      restart: always
      privileged: true
      healthcheck:
         test: [ "CMD","curl","-f", "http://localhost:5001/help" ]
         interval: 1m30s
         timeout: 10s
         retries: 3
         start_period: 40s
